-- opdracht 1
SELECT COURSES.Name, COUNT(Teachers) FROM STUDENTS, COURSES WHERE STUDENTS.ID = COURSES.STID;

-- opdracht 2
SELECT * FROM COURSES, ASSIGMENTS, STUDENTS WHERE STUDENTS.STID = ASSIGMENTS.STID


