-- opdracht 1
SELECT COURSES.Name, COUNT(Teachers) 
FROM STUDENTS, COURSES 
WHERE STUDENTS.ID = COURSES.STID;

-- opdracht 2
SELECT * 
FROM ASSIGMENTS, STUDENTS 
WHERE STUDENTS.STID = ASSIGMENTS.STID AND ASSIGMENTS.IsValid = false;

-- opdracht 3
SELECT TEACHERS.Name, COURSES.Owner, ASSIGMENTS.Owner 
FROM TEACHERS, COURSES, ASSIGMENTS 
WHERE TEACHERS.Name = COURSES.Owner AND NOT IN ASSIGMENTS.Owner;

-- opdracht 4
SELECT * FROM COURSES, STUDENTS ORDER BY STUDENTS.Enrollment_Year DESC 
WHERE COURSES.STID = STUDENTS.ID;

-- opdracht 5 TODO IM SO DONE W THIS SHEIT  
 -- Give a list of teachers that are teaching less than two classes or teachers that are teaching more than average.
SELECT AVG(COUNT(COURSES.Owner = TEACHERS.BSN)),  FROM COURSES, TEACHERS WHERE 

-- opdracht 6
SELECT STUDENTS.ID 
FROM STUDENTS, ASSIGMENTS 
WHERE STUDENTS.ID = ASSIGMENTS.STID AND ASSIGMENTS.IsValid = true;

-- opdracht 7
SELECT STUDENTS.ID 
FROM STUDENTS, TEACHERS, COURSES 
WHERE COUNT(COURSE.Owner) = COUNT(STUDENTS.Teachers INTERSECT COURSE.Owner)

-- opdracht 8
SELECT ASSIGMENTS.Owner AS Owner, COUNT(ASSIGMENTS.Owner), TEACHERS.BSN as bsn
FROM ASSIGMENTS, TEACHERS 
WHERE Owner = bsn

-- opdracht 9
SET @TempVar int = 0;
SELECT TEACHERS.Salary, COUNT(ASSIGMENTS.Owner = TEACHERS.BSN) AS totalAss,  * 
FROM TEACHERS, COURSES, ASSIGMENTS
WHERE COURSES.Owner = TEACHERS.BSN 
AND ASSIGMENTS.Owner = TEACHERS.BSN 
AND TEACHERS.Salary < 2000 + COUNT(COURSE.STID) * 0.1 + totalAss * 50 + ROUND(COUNT(COURSE.STID) + totalAss), -1) * 50;
  